version: '3.8'

services:
  # Logging stack
  loki:
    image: grafana/loki:latest
    container_name: loki-staging
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - cattlelog-staging-network
    volumes:
      - loki-data-staging:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail-staging
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ../grafana/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - cattlelog-staging-network
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-staging
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - cattlelog-staging-network
    volumes:
      - grafana-data-staging:/var/lib/grafana
      - ../grafana:/etc/grafana/provisioning
    depends_on:
      - loki

networks:
  cattlelog-staging-network:
    name: cattlelog-staging-network
    external: true

volumes:
  loki-data-staging:
  grafana-data-staging:

